### PR TITLE
Update repo with latest library versions

### PR DESCRIPTION
**Pull request by nowshad-hasan**
I've made some changes regarding these issues:

1. Create a notification channel for devices>=Oreo
2. Remove version related deprecated code from manifest and gradle files
3. Migrate to androidx
4. Update gradle distribution to 5.4.1
5. Update gradle build to 3.5.3
6. Make TargetSdkVersion to 29(android 10)
7. Make source compatibility to JAVA 1.8
8. Update version-name and version-code

### CODE REVIEW

**Comment by AntonioRedondo** [comment]
Hi @nowshad-hasan! I missed the GitHub notification for this pull request among many other notifications. 😓 Let me have a look to the changes. 👀

**Review by AntonioRedondo — APPROVED** [review]
Fantastic job! Thank you for taking the time to update the build configuration!
The app runs again in the emulator with the latest Android SDK! 👍👍👍👍👍👍👍

image

**Comment by AntonioRedondo** [comment]
@nowshad-hasan if you cannot merge the pull request tell me and I'll do it.

**Comment by nowshad-hasan** [comment]
Hi @AntonioRedondo, you can merge this pull request because I don't think I've got the permission to do it.  And really thanks for your PR review.

**Comment by nowshad-hasan** [comment]
Hi @AntonioRedondo , I accidentally made the commits with my job email not the regular email my GitHub is connected to. So, my profile is not shown up on the contributors list. Is there any workaround to solve this? Though this PR is showing on my profile. So, if it's a huge mess up for you, that will be completely unnecessary.

**Comment by AntonioRedondo** [comment]
@nowshad-hasan ouch, that really sucks! I removed last changes. Open another pull request with the right email account and I'll merged it.

**Comment by nowshad-hasan** [comment]
Hi @AntonioRedondo , I've made another PR with my regular email.

**Comment by AntonioRedondo** [comment]
image

**Comment by nowshad-hasan** [comment]
Hi @AntonioRedondo , really thanks for your effort to make the `Revert` and accept my PR again. But to get the idea, how do you revert master branch without changing the commit SHA-1 as like as before? Actually, I'm kind of noob about git!

**Comment by AntonioRedondo** [comment]
I don't think you can actually do that if you have `push`ed your changes. You can remove any number of commits in a branch, even if commits where pushed. But then any new commit will have a different hash.

What I did to revert your changes was:
```bash
git reset --hard HEAD~1 // It will erase any commit after HEAD~1, in this case, your PR changes
git push -f // We need to push to master the above changes. It's a destructive operation as we're forcing (-f) our branch history over the existing one in the repo.
```
Then merge your pull request. But the new commit in `master` will have a different hash than the one removed.

**Comment by nowshad-hasan** [comment]
Oh! That's great. Thanks for the idea 😃 .

**Pull request merged**
