### PR TITLE
Fixed the blocked app name

### PR DESCRIPTION
**Pull request by EasyVector**
Dear developer:

Hello! I am the creator of issue #19, and I have fixed the blocked app name. I would appreciate it if you could kindly revise my code and leave me some advice. Thank you so much for your precious time!

Here are screenshots after my changes:

in the largest font and display size:
copy

in the smallest display size:
copy

Thanks again! Have a nice day! :)

### CODE REVIEW

**Review by AntonioRedondo — CHANGES_REQUESTED** [review]
Hey @yuhuitech,

Thanks for this pull request.

I see the changes have many indentation reformatting. Can you just leave the few lines that are actually the new additions?

**Comment by EasyVector** [comment]
OK! I will keep the original structure of this file without reformatting it. The new version will be submitted later.

**Comment by EasyVector** [comment]
Hi! Sorry for the inconvenience, and I think I have revoked those indentation changes. (Please excuse my typo...) And thanks again! :)

**Review by AntonioRedondo — APPROVED** [review]
Cool thanks. Little great fix! I'll merge it right now.

**Pull request merged**
